### ISSUE TITLE
Plot names

### ISSUE THREAD

**Issue by didekoning** [didekoning/V2DS-Specialisatie-Titanic#2]
Verschil in namen(mr, mrs, capt, sir, etc.)
`n = length(full$Survived)
title = rep(NA,n)
for (i in 1:n){
  lastname = strsplit(full$Name[i],", ")[[1]][2]
  title[i] = strsplit(lastname,". ")[[1]][1]
}

# make a histogram of title v.s survival
d <- data.frame(title = title[1:891],Survived = train$Survived)
ggplot(d, aes(title,fill = factor(Survived))) +
    geom_histogram(stat = "count")`

**Comment by didekoning** [comment]
https://www.kaggle.com/beiqiwang/titanic/predictive-analysis-of-survival-rate-on-titanic

**Comment by tcwchris** [comment]
Issue has been resolved, only requires markdown. Not really an issue.
